/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Convite15AnosIndexRouteImport } from './routes/convite-15-anos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Convite15AnosIndexRoute = Convite15AnosIndexRouteImport.update({
  id: '/convite-15-anos/',
  path: '/convite-15-anos/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convite-15-anos/': typeof Convite15AnosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convite-15-anos': typeof Convite15AnosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convite-15-anos/': typeof Convite15AnosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/convite-15-anos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/convite-15-anos'
  id: '__root__' | '/' | '/convite-15-anos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Convite15AnosIndexRoute: typeof Convite15AnosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite-15-anos/': {
      id: '/convite-15-anos/'
      path: '/convite-15-anos'
      fullPath: '/convite-15-anos/'
      preLoaderRoute: typeof Convite15AnosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Convite15AnosIndexRoute: Convite15AnosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
